#
# A workflow to verify OTPless Erlang builds for the Android platform
# successfully.
#
# Support for Android from Linux is primary and therefore we test with all the
# architectures, STL and API levels we support.
#
name: Verify Android

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
        matrix:
          api-level: [21, 34]
          abi: [arm64-v8a, x86_64]
          stl: [c++_shared, c++_static]

    steps:
    - name: Get files
      uses: actions/checkout@v4
      with:
        path: source

    - name: Build project
      run: |
        cmake \
          -S source \
          -B build \
          -DCMAKE_SYSTEM_NAME=Android \
          -DCMAKE_SYSTEM_VERSION=${{ matrix.api-level }} \
          -DCMAKE_ANDROID_NDK=$ANDROID_NDK \
          -DCMAKE_ANDROID_ARCH_ABI=${{ matrix.abi }} \
          -DCMAKE_ANDROID_STL_TYPE=${{ matrix.stl }}
        cmake --build build --config Release

    - name: Upload artifact
      if: matrix.stl == 'c++_shared'
      uses: actions/upload-artifact@v4
      with:
        name: otpless-erlang-android-${{ matrix.api-level }}-${{ matrix.abi }}
        path: build/
