#
# A workflow to verify OTPless Erlang builds for the Android platform
# successfully.
#
name: Verify Android

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Get files
      uses: actions/checkout@v4
      with:
        path: source

    - name: Build project
      run: |
        cmake \
          -S source \
          -B build \
          -DCMAKE_SYSTEM_NAME=Android \
          -DCMAKE_SYSTEM_VERSION=21 \
          -DCMAKE_ANDROID_NDK=$ANDROID_NDK \
          -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
          -DCMAKE_ANDROID_STL_TYPE=c++_shared
        cmake --build build --config Release

    - name: Upload artifact
      if: matrix.stl == 'c++_shared'
      uses: actions/upload-artifact@v4
      with:
        name: otpless-erlang-android-21
        path: build/
