#
# A workflow to verify OTPless Erlang builds for the Windows platform
# successfully.
#
# Support for Windows is primary.
#
# XXX: Builds for ARM64 was disabled because no image with the compilation
#      tools are provided by Github.
#
name: Verify Windows

on:
  push:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        # arch: ['amd64', 'arm64']
        arch: ['amd64']
        flavor: ['emu', 'jit']

    # runs-on: windows-${{ matrix.arch }}
    runs-on: windows-2022

    steps:
    - name: Get files
      uses: actions/checkout@v4
      with:
        path: source

    - name: Build project
      run: |
        cmake -S source -B build -DERLANG_BUILD_FLAVOR=${{ matrix.flavor }}
        cmake --build build --config Release
        cmake --build build --config Debug
        cmake --install build --prefix install

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: otpless-erlang-${{ matrix.flavor }}-windows-${{ matrix.arch }}
        path: install/
