#
# A workflow to verify OTPless Erlang builds for the macOS platform
# successfully.
#
# Support for macOS is primary.
#
name: Verify macOS

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Get files
      uses: actions/checkout@v4
      with:
        path: source

    - name: Build project
      run: |
        cmake -S source -B build
        cmake --build build
        cmake --install build --prefix install

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: otpless-erlang-macos
        path: install/
