#
# A workflow to verify OTPless Erlang builds for the iOS platform successfully.
#
# Support for iOS (from macOS) is primary and therefore we test with all the
# targets.
#
# XXX: Investigate the values of the CMAKE_OSX_ARCHITECTURES and
#      CMAKE_OSX_DEPLOYMENT_TARGET variables.
#
# No debug builds for iOS.
#
name: Verify iOS

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: macos-14
    strategy:
        matrix:
          flavor: ['emu', 'jit']
          target: [device]
          # target: [device, simulator]

    steps:
    - name: Get files
      uses: actions/checkout@v4
      with:
        path: source

    - name: Install ninja
      run: brew install ninja

    - name: Build project
      run: |
        cmake \
          -S source \
          -B build \
          -G "Ninja" \
          -DCMAKE_SYSTEM_NAME=iOS \
          "-DCMAKE_OSX_ARCHITECTURES=arm64" \
          -DCMAKE_OSX_DEPLOYMENT_TARGET=14.0 \
          -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED=NO \
          -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_ALLOWED=NO \
          -DERLANG_BUILD_FLAVOR=${{ matrix.flavor }}
        cmake --build build --verbose
        cmake --install build --prefix install

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: otpless-erlang-${{ matrix.flavor }}-ios-${{ matrix.target }}
        path: install/
