#
# A workflow to verify OTPless Erlang builds for the Linux platform
# successfully.
#
name: Verify Linux

on:
  push:
    branches: [master]

jobs:
  build-debian:
    runs-on: ubuntu-latest
    container:
      image: debian:12

    steps:
    - name: Get files
      uses: actions/checkout@v4
      with:
        path: source

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y build-essential cmake

    - name: Build project
      run: |
        cmake -S source -B build
        cmake --build build --config Release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: otpless-erlang-debian
        path: build/

  build-alpine:
    runs-on: ubuntu-latest
    container:
      image: alpine:3

    steps:
    - name: Get files
      uses: actions/checkout@v4
      with:
        path: source

    - name: Install dependencies
      run: apk add --no-cache build-base cmake

    - name: Build project
      run: |
        cmake -S source -B build
        cmake --build build --config Release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: otpless-erlang-alpine
        path: build/
