#
# A workflow to verify OTPless Erlang builds for the Android platform on
# Windows successfully.
#
# Support for Android from Windows is secondary and therefore we only test with
# the default architecture (arm64-v8a) using default STL (c++_shared) and API
# level (34).
#
# No debug builds for Android.
#
name: Verify Android (on Windows)

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Get files
      uses: actions/checkout@v4
      with:
        path: source

    - name: Install ninja
      run: choco install ninja

    - name: Build project
      shell: pwsh
      run: |
        $env:ANDROID_NDK = $env:ANDROID_NDK -replace '\\', '/'
        cmake `
          -S source `
          -B build `
          -G "Ninja" `
          -DCMAKE_SYSTEM_NAME=Android `
          -DCMAKE_SYSTEM_VERSION=34 `
          -DCMAKE_ANDROID_NDK="$env:ANDROID_NDK" `
          -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a `
          -DCMAKE_ANDROID_STL_TYPE=c++_shared
        cmake --build build --config Release --verbose
        cmake --install build --prefix install

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: otpless-erlang-android
        path: install/
