#
# A workflow to verify OTPless Erlang builds for the iOS platform successfully.
#
# Support for iOS (from macOS) is primary and therefore we test with all the
# targets.
#
# XXX: Investigate the values of the CMAKE_OSX_ARCHITECTURES and
#      CMAKE_OSX_DEPLOYMENT_TARGET variables.
#
name: Verify iOS

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: macos-14
    strategy:
        matrix:
          target: [device, simulator]

    steps:
    - name: Get files
      uses: actions/checkout@v4
      with:
        path: source

    - name: Build project
      run: |
        cmake \
          -S source \
          -B build \
          -GXcode \
          -DCMAKE_SYSTEM_NAME=iOS \
          "-DCMAKE_OSX_ARCHITECTURES=arm64" \
          -DCMAKE_OSX_DEPLOYMENT_TARGET=14.0 \
          -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED=NO \
          -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_ALLOWED=NO
        if [ "${{ matrix.target }}" == "device" ]; then
          cmake --build build --config Release -- -sdk iphoneos
        else
          cmake --build build --config Release -- -sdk iphonesimulator
        fi
        cmake --install build --prefix install

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: otpless-erlang-ios-${{ matrix.target }}
        path: install/
