#
# A workflow to verify OTPless Erlang builds for the macOS platform
# successfully.
#
# Support for macOS is primary.
#
name: Verify macOS

on:
  push:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        flavor: ['emu', 'jit']

    runs-on: macos-14

    steps:
    - name: Get files
      uses: actions/checkout@v4
      with:
        path: source

    - name: Build project
      run: |
        cmake -S source -B build -DERLANG_BUILD_FLAVOR=${{ matrix.flavor }}
        cmake --build build --verbose
        cmake --install build --prefix install

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: otpless-erlang-${{ matrix.flavor }}-macos
        path: install/

    - name: Build project (debug)
      run: |
        cmake -S source -B build-debug -DERLANG_BUILD_TYPE=debug -DERLANG_BUILD_FLAVOR=${{ matrix.flavor }}
        cmake --build build-debug --verbose
        cmake --install build-debug --prefix install-debug

    - name: Upload artifact (debug)
      uses: actions/upload-artifact@v4
      with:
        name: otpless-erlang-${{ matrix.flavor }}-macos-debug
        path: install-debug/
